### ISSUE TITLE
星星充电

### ISSUE THREAD

**Issue by jackwoodys** [shengetui/qx#2]
佬哥，星星充电的青龙参数和变更是不是XXCD_KEY=[{eyj***}]
若没错的话，在青龙运行里提示

## 开始执行... 2024-04-10 15:17:01

🔔星星充电, 开始!
===== 账号 开始执行 =====
🔔星星充电, 结束! 🕛 0.818 秒

没有其它的日志输出了，

另外多账号的连接符是什么，@，#，/n，请佬哥明示，谢谢

**Comment by shengetui** [comment]
没有日志输出那是因为，token失效或者不正确，现在加上签到返回的日志了。另外   没有设置多账号签到的功能，因为这个签到福利小又少，你要是有能力可以复制源码添加多账号的功能。
